### ISSUE TITLE
Issue with RX 6800 XT or Xeon E5 v4

### ISSUE THREAD

**Issue by seakrebel** [marlonmnz/EFI-X99-MACHINIST-RS9-RX6600M#1]
Hello, do you have any idea why your EFI wouldn't boot with an RX 6800 XT or Xeon E5 2698 v4 ?
I have the same motherboard, and already changed the following BIOS Settings:

Fast Boot - **disabled**
Secure Boot - **disabled**
Serial/COM Port - **disabled**
Parallel Port - couldn't find
VT-d - **disabled**
Compatibility Support Module (CSM) - **disabled**
Thunderbolt - couldn't find
Intel SGX - couldn't find
Intel Platform Trust - couldn't find
CFG Lock (MSR 0xE2 write protection) - **disabled**

VT-x - couldn't find
Above 4G decoding - **enabled**
Hyper-Threading - **enabled**
Execute Disable Bit - **enabled**
EHCI/XHCI Hand-off - **enabled**
OS type: Windows 8.1/10/11 UEFI Mode - couldn't find
SATA Mode: **AHCI**

![2022-11-29 00 11 27](https://user-images.githubusercontent.com/16282150/204400090-3950abcf-9c54-45d3-a776-075b256e0b61.jpg)

**Comment by SouEuMarlon** [comment]
Hello! 
Hmmm I really don't know why does't working for you, but I followed a Gabriel Luchina tutorial. Maybe the vídeo can help you too.

My Xeon is a V3, so I don't know if this is the couse of your issue.

ps: He has a Discord serve with International support. The link for that is in video description.

https://youtu.be/Pxm2FXy4Mts

**Comment by seakrebel** [comment]
I solved it, the issue was in the way I prepared my USB drive. It didn't work when I used the full (offline) version of installer, prepared with "createinstallmedia".
But it worked when I was using BaseSystem.dmg (online installer) and prepared as in the video you linked. 
Thank you very much!
