### ISSUE TITLE
How your bootloader works with this hardware configuration

### ISSUE THREAD

**Issue by Boojin** [marlonmnz/EFI-X99-MACHINIST-RS9-RX6600M#2]
Hello!
Please tell me, can I use your bootloader to install and then work on the Monterey system?
```
Plataform: Desktop | Intel Xeon
Motherboard: MACHINIST X99-RS9
CPU: Intel Xeon E5-2630 v3, 2400 MHz (8C/16T)
GPU: Radeon RX 570  (4 GB)
Audio: Realtek ALC662
```

**Comment by SouEuMarlon** [comment]
> Hello! Please tell me, can I use your bootloader to install and then work on the Monterey system?
> 
> ```
> Plataform: Desktop | Intel Xeon
> Motherboard: MACHINIST X99-RS9
> CPU: Intel Xeon E5-2630 v3, 2400 MHz (8C/16T)
> GPU: Radeon RX 570  (4 GB)
> Audio: Realtek ALC662
> ```

Hi!
I guess it's works, but I recommend you start with Catalina to make USB Mapping and install the correct audio drivers. After that and if you Hackintosh is workin' you'll can upgrade to superior macOS versions.
